[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "more absurd shoot patient convince goat lemon banner toss marine offer toast hazard toilet disorder distance test pattern body toward input pigeon enact laugh"
